version: 2.1

orbs:
  android: circleci/android@2.4.0
  codecov: codecov/codecov@3.2.2

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.09.1
    working_directory: ~/project

jobs:
  build-and-test:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Restore Gradle cache
          command: ./gradlew dependencies

      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest

      - run:
          name: Generate Jacoco Merged Report
          command: ./gradlew jacocoMergedReport

      - run:
          name: Show Coverage Output
          command: ls -R build/reports/jacoco

      - codecov/upload:
          file: build/reports/jacoco/jacocoMergedReport/xml/report.xml
          flags: android
          name: codecov-android

workflows:
  version: 2
  test-and-report:
    jobs:
      - build-and-test
