version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.01
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Set executable permission to Gradle
          command: chmod +x ./gradlew

      - run:
          name: Run Unit Tests (app & core)
          command: ./gradlew :app:testDebugUnitTest :core:testDebugUnitTest

      - run:
          name: Generate Jacoco Coverage Report (optional)
          command: ./gradlew jacocoTestReport

      - run:
          name: Upload Coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

workflows:
  version: 2
  test:
    jobs:
      - build
